version: "3"

services:
  weatherconsumer:
    container_name: weatherconsumer
    image: consumer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: weather
      SINK_TOPIC_NAME: weathersink
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u", "python/weather_consumer.py"]
  fakerconsumer:
    container_name: fakerconsumer
    image: consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: faker
      SINK_TOPIC_NAME: fakersink
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u", "python/faker_consumer.py"]
  wikipediaconsumer:
    container_name: wikipediaconsumer
    image: consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: wikipedia
      SINK_TOPIC_NAME: wikipediasink
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u", "python/wikipedia_consumer.py"]

networks:
  default:
    external:
      name: kafka-network
